---
- include: preflight.yml

- name: Create the DigitalOcean Exporter group
  group:
    name: "{{ __digitalocean_exporter_group }}"
    state: present
    system: true

- name: Create the DigitalOcean Exporter user
  user:
    name: "{{ __digitalocean_exporter_user }}"
    groups: "{{ __digitalocean_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
    home: /

- name: Download digitalocean_exporter binary
  become: false
  get_url:
    url: "https://github.com/Amygos/digitalocean_exporter/releases/download/{{ digitalocean_exporter_version }}/digitalocean_exporter"
    dest: "/tmp/digitalocean_exporter-{{ digitalocean_exporter_version }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Propagate digitalocean_exporter binaries
  copy:
    src: "/tmp/digitalocean_exporter-{{ digitalocean_exporter_version }}"
    dest: "/usr/local/bin/digitalocean_exporter"
    remote_src: true
    mode: 0755
    owner: root
    group: root
  notify:
    - restart digitalocean exporter
  when: not ansible_check_mode

- name: Copy the digitalocean_exporter systemd service file
  template:
    src: digitalocean_exporter.service.j2
    dest: /etc/systemd/system/digitalocean_exporter.service
    owner: root
    group: root
    mode: 0644
  no_log: "{{ not lookup('env', 'ANSIBLE_DEBUG') | bool }}"
  notify:
    - restart digitalocean exporter

- name: Ensure digitalocean_exporter is enabled on boot
  systemd:
    daemon_reload: true
    name: digitalocean_exporter
    enabled: true
